# שם האפליקציה
spring.application.name=demo

# הגדרת הפורט של השרת (כדי שיתאים ל-React)
server.port=8081

# הגדרות בסיס הנתונים H2 בזיכרון (In-Memory)
spring.datasource.url=jdbc:h2:mem:flightdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# הפעלת ממשק הניהול H2 Console בדפדפן
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# הגדרות ה-ORM ליצירה אוטומטית ונקייה של כל 3 הטבלאות בכל הרצה
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# מניעת אזהרות מיותרות בטרמינל בזמן הריצה
spring.jpa.open-in-view=false